name: Test PR workflow
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files in root
        run: ls -la
      - name: Test npm
        run: |
          node -v
          npm -v
          echo "Workflow rodando no root"
